"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "../lib/wardrobeApi";

const STYLES=["简约","通勤","轻复古","松弛","运动","街头","甜美","优雅"];
const GARMENTS=["衬衫","针织","卫衣","牛仔裤","西裤","半身裙","连衣裙","外套","运动鞋","皮鞋"];
const BOUNDARIES=["我偏怕冷","不穿高跟鞋","优先适合步行","避免过度紧身"];
const TITLES=["","先认识你的日常","你喜欢什么风格？","哪些风格不像你？","你最爱穿什么？","哪些衣服尽量别推荐？","最后确认舒适边界"];
type ExistingProfile={height_cm:number|null;preferred_colors:string[];avoided_colors:string[];visual_goals:string[];photo_retention_consent:boolean;temperature_preference:string;preferred_styles:string[];avoided_styles:string[];preferred_item_terms:string[];avoided_item_terms:string[];restrictions:string[]};

function ChoiceGrid({options,selected,onToggle,tone="like"}:{options:string[];selected:string[];onToggle:(value:string)=>void;tone?:"like"|"avoid"}){return <div className="toolbar">{options.map(value=><button type="button" aria-pressed={selected.includes(value)} className={`button ${selected.includes(value)?tone==="avoid"?"choice-avoid":"button-primary":"button-soft"}`} key={value} onClick={()=>onToggle(value)}>{value}</button>)}</div>}

export default function Onboarding(){
  const router=useRouter();const[step,setStep]=useState(1);const[occasion,setOccasion]=useState("");const[likedStyles,setLikedStyles]=useState<string[]>([]);const[avoidedStyles,setAvoidedStyles]=useState<string[]>([]);const[likedItems,setLikedItems]=useState<string[]>([]);const[avoidedItems,setAvoidedItems]=useState<string[]>([]);const[boundaries,setBoundaries]=useState<string[]>([]);const[existing,setExisting]=useState<ExistingProfile|null>(null);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
  useEffect(()=>{apiRequest<ExistingProfile|null>("/api/v1/profile").then(profile=>{if(!profile)return;setExisting(profile);setLikedStyles(profile.preferred_styles||[]);setAvoidedStyles(profile.avoided_styles||[]);setLikedItems(profile.preferred_item_terms||[]);setAvoidedItems(profile.avoided_item_terms||[]);setBoundaries([...(profile.temperature_preference==="怕冷"?["我偏怕冷"]:[]),...(profile.restrictions||[]).filter(value=>!value.startsWith("常见场合："))]);const savedOccasion=(profile.restrictions||[]).find(value=>value.startsWith("常见场合："));if(savedOccasion)setOccasion(savedOccasion.slice(5))}).catch(()=>undefined)},[]);
  const toggle=(value:string,values:string[],setter:(next:string[])=>void,opposite:string[]=[],setOpposite?:(next:string[])=>void)=>{setter(values.includes(value)?values.filter(item=>item!==value):[...values,value]);if(setOpposite)setOpposite(opposite.filter(item=>item!==value))};
  async function finish(){setSaving(true);setMessage("");try{await apiRequest("/api/v1/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({height_cm:existing?.height_cm??null,temperature_preference:boundaries.includes("我偏怕冷")?"怕冷":"",preferred_styles:likedStyles,avoided_styles:avoidedStyles,preferred_item_terms:likedItems,avoided_item_terms:avoidedItems,preferred_colors:existing?.preferred_colors||[],avoided_colors:existing?.avoided_colors||[],restrictions:[...boundaries.filter(value=>value!=="我偏怕冷"),...(occasion?[`常见场合：${occasion}`]:[])],visual_goals:existing?.visual_goals||[],photo_retention_consent:existing?.photo_retention_consent||false})});const returnToSettings=window.location.search.includes("return=settings");router.push(returnToSettings?"/settings/privacy":"/wardrobe/upload?from=onboarding")}catch(error){setMessage(error instanceof Error?error.message:"偏好保存失败")}finally{setSaving(false)}}
  return <main style={{maxWidth:820,margin:"auto",padding:"55px 20px"}}><div className="brand"><span className="brand-mark">衣</span>衣序</div><div className="progress"><span style={{width:`${step/6*100}%`}}/></div><div className="card" style={{marginTop:25,padding:32}}><div className="eyebrow">STEP {step} / 6</div><h1 className="title">{TITLES[step]}</h1>
    {step===1&&<div><div className="field"><label>最常需要搭配的场合</label><select className="input" value={occasion} onChange={event=>setOccasion(event.target.value)}><option value="">暂不选择</option><option>通勤 / 商务休闲</option><option>校园 / 日常</option><option>居家 / 休闲</option><option>约会 / 社交</option></select></div><p className="subtle">没有默认答案；不选择也可以继续，之后可随时修改。</p></div>}
    {step===2&&<><p className="subtle">可以多选。它们会提高相应单品在推荐中的优先级。</p><ChoiceGrid options={STYLES} selected={likedStyles} onToggle={value=>toggle(value,likedStyles,setLikedStyles,avoidedStyles,setAvoidedStyles)}/></>}
    {step===3&&<><p className="subtle">选择真正不喜欢的即可；系统会尽量排除带有这些风格标签的衣物。</p><ChoiceGrid tone="avoid" options={STYLES} selected={avoidedStyles} onToggle={value=>toggle(value,avoidedStyles,setAvoidedStyles,likedStyles,setLikedStyles)}/></>}
    {step===4&&<><p className="subtle">常穿、好搭或让你觉得自在的衣类。</p><ChoiceGrid options={GARMENTS} selected={likedItems} onToggle={value=>toggle(value,likedItems,setLikedItems,avoidedItems,setAvoidedItems)}/></>}
    {step===5&&<><p className="subtle">系统不会用这些衣类凑数；之后可在“我的”里修改。</p><ChoiceGrid tone="avoid" options={GARMENTS} selected={avoidedItems} onToggle={value=>toggle(value,avoidedItems,setAvoidedItems,likedItems,setLikedItems)}/></>}
    {step===6&&<div>{BOUNDARIES.map(value=><button type="button" className="toggle-row onboarding-toggle" aria-pressed={boundaries.includes(value)} key={value} onClick={()=>toggle(value,boundaries,setBoundaries)}><b>{value}</b><span className={`toggle ${boundaries.includes(value)?"active":""}`}/></button>)}<div className="empty-upload" style={{minHeight:140,marginTop:20}}><div><b>下一步：录入 5～8 件常穿衣物</b><p className="subtle">整身照、多张商品图都可以，系统会自动拆分并识别。</p></div></div></div>}
    {message&&<p className="pill orange">{message}</p>}<div className="toolbar" style={{marginTop:28,justifyContent:"flex-end"}}>{step>1&&<button className="button button-ghost" onClick={()=>setStep(step-1)}>上一步</button>}{step<6?<button className="button button-primary" onClick={()=>setStep(step+1)}>继续</button>:<button className="button button-primary" disabled={saving} onClick={finish}>{saving?"正在保存…":"保存偏好并开始录衣"}</button>}</div></div></main>
}
