"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "../../components/AppShell";
import { apiRequest } from "../../lib/wardrobeApi";

type Profile={height_cm:number|null;temperature_preference:string;preferred_styles:string[];avoided_styles:string[];preferred_item_terms:string[];avoided_item_terms:string[];preferred_colors:string[];avoided_colors:string[];restrictions:string[];visual_goals:string[];photo_retention_consent:boolean};
type Integration={provider:string;status:string};
type Notification={enabled:boolean;important_events_only:boolean;weather_change_threshold:number;reminder_time:string;quiet_hours:string;channels:string[]};
type ClosetPlan={functional_gaps:string[];duplicate_warnings:string[];low_usage_item_ids:string[];style_evolution:string};
type Identity={signature_colors:string[];silhouettes:string[];narrative:string;confidence:number};
type Purchase={decision:string;compatibility_score:number;duplication_score:number;valid_outfit_count:number;explanation:string};
const empty:Profile={height_cm:null,temperature_preference:"",preferred_styles:[],avoided_styles:[],preferred_item_terms:[],avoided_item_terms:[],preferred_colors:[],avoided_colors:[],restrictions:[],visual_goals:[],photo_retention_consent:false};
const defaultNotice:Notification={enabled:true,important_events_only:true,weather_change_threshold:5,reminder_time:"20:30",quiet_hours:"22:00-07:30",channels:["in_app"]};

export default function Mine(){
  const [profile,setProfile]=useState<Profile>(empty),[integrations,setIntegrations]=useState<Integration[]>([]),[notification,setNotification]=useState(defaultNotice),[closet,setCloset]=useState<ClosetPlan|null>(null),[identity,setIdentity]=useState<Identity|null>(null),[logs,setLogs]=useState<Record<string,unknown>[]>([]),[status,setStatus]=useState("");
  const [product,setProduct]=useState(""),[category,setCategory]=useState("上装"),[color,setColor]=useState(""),[purchase,setPurchase]=useState<Purchase|null>(null);
  const load=()=>Promise.all([apiRequest<Profile|null>("/api/v1/profile"),apiRequest<Integration[]>("/api/v1/integrations"),apiRequest<Notification>("/api/v1/notification-preferences"),apiRequest<ClosetPlan>("/api/v1/long-term-plan"),apiRequest<Record<string,unknown>[]>("/api/v1/privacy/access-log")]).then(([p,i,n,c,l])=>{if(p)setProfile(p);setIntegrations(i);setNotification(n);setCloset(c);setLogs(l);const result=new URLSearchParams(location.search).get("outlook");if(result)setStatus(result==="connected"?"Outlook 日历已连接":"Outlook 日历连接失败，请检查 Microsoft 应用配置")}).catch(error=>setStatus(error.message));
  useEffect(()=>{void load()},[]);
  const list=(value:string)=>value.split(/[，,]/).map(item=>item.trim()).filter(Boolean);
  const save=async()=>{try{await Promise.all([apiRequest("/api/v1/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)}),apiRequest("/api/v1/notification-preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(notification)})]);setStatus("设置已保存") }catch(error){setStatus(error instanceof Error?error.message:"保存失败")}};
  const connected=(provider:string)=>integrations.some(item=>item.provider===provider&&item.status==="connected");
  const toggleOutlook=async()=>{try{if(connected("outlook")){await apiRequest("/api/v1/integrations/outlook",{method:"DELETE"});await load();setStatus("Outlook 日历授权已撤回")}else{const result=await apiRequest<{authorization_url:string}>("/api/v1/integrations/outlook/authorize");location.href=result.authorization_url}}catch(error){setStatus(error instanceof Error?error.message:"操作失败")}};
  const rebuildIdentity=async()=>{try{setIdentity(await apiRequest("/api/v1/style-identity/rebuild",{method:"POST"}))}catch(error){setStatus(error instanceof Error?error.message:"风格读取失败")}};
  const analyzePurchase=async()=>{if(!color.trim()){setStatus("请填写商品颜色");return}try{setPurchase(await apiRequest("/api/v1/purchase/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:product||`${color}${category}`,category,colors:list(color),styles:[],material:null,price:null})}))}catch(error){setStatus(error instanceof Error?error.message:"分析失败")}};
  const remove=()=>{if(!window.confirm("确定提交删除照片与个人画像的请求吗？该操作进入后端队列后不可在页面撤销。"))return;apiRequest("/api/v1/privacy/deletion-requests?scope=photos_and_profile",{method:"POST"}).then(()=>setStatus("删除请求已提交")).catch(error=>setStatus(error.message))};
  return <AppShell title="我的"><div className="section-head" style={{marginTop:0}}><div><h1 className="title">我的风格与设置</h1><p className="subtle">常用偏好放在前面，低频工具按需展开。权限随时撤回。</p></div><Link className="button button-ghost" href="/onboarding?return=settings">重新设置穿搭偏好</Link></div>
    <section className="card form-grid">
      <div className="field"><label>体感偏好</label><select className="input" value={profile.temperature_preference} onChange={event=>setProfile({...profile,temperature_preference:event.target.value})}><option value="">未设置</option><option>怕冷</option><option>中性</option><option>怕热</option></select></div>
      <div className="field"><label>喜欢的风格</label><input className="input" value={profile.preferred_styles.join("，")} onChange={event=>setProfile({...profile,preferred_styles:list(event.target.value)})}/></div>
      <div className="field"><label>不喜欢的风格</label><input className="input" value={profile.avoided_styles.join("，")} onChange={event=>setProfile({...profile,avoided_styles:list(event.target.value)})}/></div>
      <div className="field"><label>喜欢的衣类</label><input className="input" value={profile.preferred_item_terms.join("，")} onChange={event=>setProfile({...profile,preferred_item_terms:list(event.target.value)})}/></div>
      <div className="field"><label>尽量不推荐的衣类</label><input className="input" value={profile.avoided_item_terms.join("，")} onChange={event=>setProfile({...profile,avoided_item_terms:list(event.target.value)})}/></div>
      <div className="field"><label>喜欢的颜色</label><input className="input" value={profile.preferred_colors.join("，")} onChange={event=>setProfile({...profile,preferred_colors:list(event.target.value)})}/></div>
      <div className="field"><label>不喜欢的颜色</label><input className="input" value={profile.avoided_colors.join("，")} onChange={event=>setProfile({...profile,avoided_colors:list(event.target.value)})}/></div>
      <div className="field"><label>其他穿着限制</label><input className="input" value={profile.restrictions.join("，")} onChange={event=>setProfile({...profile,restrictions:list(event.target.value)})}/></div>
      <button className="button button-primary" onClick={save}>保存设置</button>
    </section>

    <div className="grid grid-2" style={{marginTop:16}}><details className="card"><summary><b>提醒与数据授权</b></summary><label className="toggle-row"><span>重要日程和天气变化提醒</span><input type="checkbox" checked={notification.enabled} onChange={event=>setNotification({...notification,enabled:event.target.checked})}/></label><div className="item-row"><div><b>Microsoft Outlook 日历（只读）</b><p className="subtle">通过 Microsoft OAuth 读取近期日程</p></div><span className="spacer"/><button className="button button-ghost" onClick={toggleOutlook}>{connected("outlook")?"撤回":"连接"}</button></div><div className="item-row"><div><b>Open-Meteo 天气</b><p className="subtle">无需账号或 API Key，按城市获取实时天气</p></div><span className="spacer"/><span className="pill green">已启用</span></div></details>
      <details className="card"><summary><b>我的风格</b></summary>{identity?<><p>{identity.narrative}</p><p className="subtle">常用颜色：{identity.signature_colors.join("、")||"记录不足"} · 置信度 {Math.round(identity.confidence*100)}%</p></>:<p className="subtle">根据真实采用记录生成，不分析敏感身体属性。</p>}<button className="button button-ghost" onClick={rebuildIdentity}>查看我的风格</button></details>
      <details className="card"><summary><b>这件值得买吗？</b></summary><div className="form-grid" style={{marginTop:14}}><div className="field"><label>商品</label><input className="input" value={product} onChange={event=>setProduct(event.target.value)} placeholder="米白针织开衫"/></div><div className="field"><label>品类</label><select className="input" value={category} onChange={event=>setCategory(event.target.value)}>{["上装","下装","连衣裙","鞋履","包袋","外套"].map(value=><option key={value}>{value}</option>)}</select></div><div className="field"><label>颜色</label><input className="input" value={color} onChange={event=>setColor(event.target.value)}/></div><button className="button button-ghost" onClick={analyzePurchase}>和衣橱比一比</button></div>{purchase&&<div className="card-flat" style={{marginTop:12}}><b>{purchase.decision}</b><p>{purchase.explanation}</p><p className="subtle">可搭 {purchase.valid_outfit_count} 套 · 兼容度 {Math.round(purchase.compatibility_score*100)}%</p></div>}</details>
      <details className="card"><summary><b>衣橱建议</b></summary>{closet?<><p>低频衣物 {closet.low_usage_item_ids.length} 件</p>{closet.functional_gaps.map(value=><p key={value}>{value}</p>)}{closet.duplicate_warnings.map(value=><p className="subtle" key={value}>{value}</p>)}<p>{closet.style_evolution}</p></>:<p className="subtle">暂时没有需要处理的建议。</p>}</details>
      <details className="card"><summary><b>数据与隐私</b></summary><label className="toggle-row"><span>允许保留分析照片</span><input type="checkbox" checked={profile.photo_retention_consent} onChange={event=>setProfile({...profile,photo_retention_consent:event.target.checked})}/></label><h3>最近访问日志</h3>{logs.slice(0,8).map((item,index)=><p className="subtle" key={index}>{String(item.action||"")} · {String(item.purpose||"")}</p>)}{!logs.length&&<p className="subtle">暂无访问记录</p>}<button className="button button-ghost" onClick={remove}>删除照片与个人资料</button></details></div>
    {status&&<div className="toast">{status}</div>}
  </AppShell>
}
