from .time_utils import datetime
from sqlalchemy import String, Integer, Float, Boolean, DateTime, ForeignKey, JSON, Text
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base

class User(Base):
    __tablename__="users"; id:Mapped[str]=mapped_column(String,primary_key=True); email:Mapped[str|None]=mapped_column(String,unique=True); password_hash:Mapped[str|None]=mapped_column(String); password_salt:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AuthSession(Base):
    __tablename__="auth_sessions"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); expires_at:Mapped[datetime]=mapped_column(DateTime,index=True); revoked_at:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class UserProfile(Base):
    __tablename__="user_profiles"; user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),primary_key=True); height_cm:Mapped[int|None]=mapped_column(Integer); temperature_preference:Mapped[str]=mapped_column(String,default=""); preferred_styles:Mapped[list]=mapped_column(JSON,default=list); avoided_styles:Mapped[list]=mapped_column(JSON,default=list); preferred_item_terms:Mapped[list]=mapped_column(JSON,default=list); avoided_item_terms:Mapped[list]=mapped_column(JSON,default=list); preferred_colors:Mapped[list]=mapped_column(JSON,default=list); avoided_colors:Mapped[list]=mapped_column(JSON,default=list); restrictions:Mapped[list]=mapped_column(JSON,default=list); visual_goals:Mapped[list]=mapped_column(JSON,default=list); photo_retention_consent:Mapped[bool]=mapped_column(Boolean,default=False)
class WardrobeItem(Base):
    __tablename__="wardrobe_items"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); category:Mapped[str]=mapped_column(String,index=True); subcategory:Mapped[str]=mapped_column(String); colors:Mapped[list]=mapped_column(JSON,default=list); material_guess:Mapped[list]=mapped_column(JSON,default=list); material_confidence:Mapped[float]=mapped_column(Float,default=0); pattern:Mapped[str]=mapped_column(String,default="纯色"); fit:Mapped[str]=mapped_column(String,default="常规"); length:Mapped[str]=mapped_column(String,default="常规"); wearing_layer:Mapped[str]=mapped_column(String,default="主上装"); warmth_level:Mapped[int]=mapped_column(Integer,default=2); formality_level:Mapped[int]=mapped_column(Integer,default=2); styles:Mapped[list]=mapped_column(JSON,default=list); seasons:Mapped[list]=mapped_column(JSON,default=list); weather_constraints:Mapped[list]=mapped_column(JSON,default=list); clean_status:Mapped[str]=mapped_column(String,default="可穿",index=True); wear_count:Mapped[int]=mapped_column(Integer,default=0); last_worn_at:Mapped[datetime|None]=mapped_column(DateTime); image_asset_id:Mapped[str|None]=mapped_column(ForeignKey("image_assets.id"),index=True,unique=True); image_url:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ImageAsset(Base):
    __tablename__="image_assets"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); kind:Mapped[str]=mapped_column(String,index=True); storage_backend:Mapped[str]=mapped_column(String); bucket:Mapped[str|None]=mapped_column(String); object_key:Mapped[str]=mapped_column(String,unique=True); original_filename:Mapped[str]=mapped_column(String); content_type:Mapped[str]=mapped_column(String); byte_size:Mapped[int]=mapped_column(Integer); sha256:Mapped[str|None]=mapped_column(String); width:Mapped[int|None]=mapped_column(Integer); height:Mapped[int|None]=mapped_column(Integer); variants:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[str]=mapped_column(String,default="pending",index=True); deleted_at:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Outfit(Base):
    __tablename__="outfits"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); mode:Mapped[str]=mapped_column(String); occasion:Mapped[str]=mapped_column(String); item_ids:Mapped[list]=mapped_column(JSON); result:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class OutfitFeedback(Base):
    __tablename__="outfit_feedback"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); outfit_id:Mapped[str]=mapped_column(ForeignKey("outfits.id"),index=True); adopted:Mapped[bool]=mapped_column(Boolean); replaced_item_ids:Mapped[list]=mapped_column(JSON,default=list); feedback_tags:Mapped[list]=mapped_column(JSON,default=list); free_text:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class WearHistory(Base):
    __tablename__="wear_history"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); outfit_id:Mapped[str]=mapped_column(String,index=True); worn_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PhotoAsset(Base):
    __tablename__="user_photo_assets"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); kind:Mapped[str]=mapped_column(String); storage_key:Mapped[str]=mapped_column(String); retention:Mapped[str]=mapped_column(String,default="temporary"); deleted_at:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ConsentRecord(Base):
    __tablename__="consent_records"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); scope:Mapped[str]=mapped_column(String); granted:Mapped[bool]=mapped_column(Boolean); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class DeletionRequest(Base):
    __tablename__="deletion_requests"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); scope:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="queued"); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AgentRun(Base):
    __tablename__="agent_runs"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); model:Mapped[str]=mapped_column(String); prompt_version:Mapped[str]=mapped_column(String); latency_ms:Mapped[int]=mapped_column(Integer,default=0); status:Mapped[str]=mapped_column(String); error:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ImageTask(Base):
    __tablename__="image_generation_tasks"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); kind:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="queued"); result_url:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)

class ContextProfile(Base):
    __tablename__="context_profiles"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); context_key:Mapped[str]=mapped_column(String,index=True); weights:Mapped[dict]=mapped_column(JSON); preferences:Mapped[dict]=mapped_column(JSON,default=dict); sample_count:Mapped[int]=mapped_column(Integer,default=0); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class BehaviorFeature(Base):
    __tablename__="behavior_features"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); context_key:Mapped[str]=mapped_column(String,index=True); feature_key:Mapped[str]=mapped_column(String,index=True); value:Mapped[float]=mapped_column(Float); evidence_count:Mapped[int]=mapped_column(Integer,default=1); source:Mapped[str]=mapped_column(String); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class WardrobeRelation(Base):
    __tablename__="wardrobe_item_relations"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); source_item_id:Mapped[str]=mapped_column(String,index=True); target_item_id:Mapped[str]=mapped_column(String,index=True); relation_type:Mapped[str]=mapped_column(String,default="pairs_with"); score:Mapped[float]=mapped_column(Float); evidence:Mapped[dict]=mapped_column(JSON,default=dict); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class WeeklyPlan(Base):
    __tablename__="weekly_plans"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); start_date:Mapped[str]=mapped_column(String,index=True); status:Mapped[str]=mapped_column(String,default="active"); version:Mapped[int]=mapped_column(Integer,default=1); summary:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PlanDay(Base):
    __tablename__="plan_days"; id:Mapped[str]=mapped_column(String,primary_key=True); plan_id:Mapped[str]=mapped_column(ForeignKey("weekly_plans.id"),index=True); date:Mapped[str]=mapped_column(String,index=True); occasion:Mapped[str]=mapped_column(String); weather:Mapped[dict]=mapped_column(JSON); item_ids:Mapped[list]=mapped_column(JSON); status:Mapped[str]=mapped_column(String,default="planned"); explanation:Mapped[dict]=mapped_column(JSON,default=dict); affected_by:Mapped[list]=mapped_column(JSON,default=list)
class TravelPlan(Base):
    __tablename__="travel_plans"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); destination:Mapped[str]=mapped_column(String); start_date:Mapped[str]=mapped_column(String); end_date:Mapped[str]=mapped_column(String); constraints:Mapped[dict]=mapped_column(JSON); result:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class StyleIdentity(Base):
    __tablename__="style_identities"; user_id:Mapped[str]=mapped_column(String,primary_key=True); signature_colors:Mapped[list]=mapped_column(JSON); silhouettes:Mapped[list]=mapped_column(JSON); core_item_ids:Mapped[list]=mapped_column(JSON); preferred_formality:Mapped[float]=mapped_column(Float,default=3); exploration_range:Mapped[dict]=mapped_column(JSON); context_expressions:Mapped[dict]=mapped_column(JSON); evolution:Mapped[list]=mapped_column(JSON); confidence:Mapped[float]=mapped_column(Float,default=0); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AuthorizedIntegration(Base):
    __tablename__="authorized_integrations"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); provider:Mapped[str]=mapped_column(String); scopes:Mapped[list]=mapped_column(JSON); status:Mapped[str]=mapped_column(String,default="disconnected"); encrypted_credential_ref:Mapped[str|None]=mapped_column(String); last_synced_at:Mapped[datetime|None]=mapped_column(DateTime); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ProactiveEvent(Base):
    __tablename__="proactive_events"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); event_type:Mapped[str]=mapped_column(String,index=True); importance:Mapped[float]=mapped_column(Float); scheduled_for:Mapped[datetime]=mapped_column(DateTime,index=True); payload:Mapped[dict]=mapped_column(JSON); status:Mapped[str]=mapped_column(String,default="pending"); dedupe_key:Mapped[str]=mapped_column(String,index=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class NotificationPreference(Base):
    __tablename__="notification_preferences"; user_id:Mapped[str]=mapped_column(String,primary_key=True); enabled:Mapped[bool]=mapped_column(Boolean,default=True); important_events_only:Mapped[bool]=mapped_column(Boolean,default=True); weather_change_threshold:Mapped[float]=mapped_column(Float,default=5); reminder_time:Mapped[str]=mapped_column(String,default="20:30"); quiet_hours:Mapped[str]=mapped_column(String,default="22:00-07:30"); channels:Mapped[list]=mapped_column(JSON,default=lambda:["in_app"])
class MultiScenePlan(Base):
    __tablename__="multi_scene_plans"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); date:Mapped[str]=mapped_column(String); scenes:Mapped[list]=mapped_column(JSON); base_item_ids:Mapped[list]=mapped_column(JSON); transitions:Mapped[list]=mapped_column(JSON); carry_item_ids:Mapped[list]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PurchaseAnalysis(Base):
    __tablename__="purchase_analyses"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); candidate:Mapped[dict]=mapped_column(JSON); result:Mapped[dict]=mapped_column(JSON); decision:Mapped[str]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class RecommendationEvidence(Base):
    __tablename__="recommendation_evidence"; id:Mapped[int]=mapped_column(Integer,primary_key=True); outfit_id:Mapped[str]=mapped_column(String,index=True); dimension:Mapped[str]=mapped_column(String); score:Mapped[float]=mapped_column(Float); reasons:Mapped[list]=mapped_column(JSON); source_refs:Mapped[list]=mapped_column(JSON,default=list)
class RecommendationDecision(Base):
    __tablename__="recommendation_decisions"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); context_key:Mapped[str]=mapped_column(String,index=True); request_snapshot:Mapped[dict]=mapped_column(JSON); candidate_generator_version:Mapped[str]=mapped_column(String,default="rules-v2"); feature_schema_version:Mapped[str]=mapped_column(String,default="features-v3"); ranking_model_version:Mapped[str]=mapped_column(String,default="rules-v1"); policy_version:Mapped[str]=mapped_column(String,default="pairwise-control-v1"); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True)
class CandidateImpression(Base):
    __tablename__="candidate_impressions"; id:Mapped[str]=mapped_column(String,primary_key=True); decision_id:Mapped[str]=mapped_column(ForeignKey("recommendation_decisions.id"),index=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); item_ids:Mapped[list]=mapped_column(JSON); feature_snapshot:Mapped[dict]=mapped_column(JSON); base_score:Mapped[float]=mapped_column(Float); predicted_probability:Mapped[float]=mapped_column(Float); uncertainty:Mapped[float]=mapped_column(Float,default=0); final_score:Mapped[float]=mapped_column(Float); position:Mapped[int|None]=mapped_column(Integer); displayed:Mapped[bool]=mapped_column(Boolean,default=False,index=True); selection_probability:Mapped[float]=mapped_column(Float,default=0); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True)
class DecisionOutcome(Base):
    __tablename__="decision_outcomes"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); decision_id:Mapped[str]=mapped_column(ForeignKey("recommendation_decisions.id"),index=True); impression_id:Mapped[str]=mapped_column(ForeignKey("candidate_impressions.id"),index=True); outfit_id:Mapped[str]=mapped_column(ForeignKey("outfits.id"),index=True); reward:Mapped[float]=mapped_column(Float); adopted:Mapped[bool]=mapped_column(Boolean); source:Mapped[str]=mapped_column(String,default="user_feedback",index=True); replaced_item_ids:Mapped[list]=mapped_column(JSON,default=list); feedback_delay_seconds:Mapped[int]=mapped_column(Integer,default=0); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True)
class RankingModel(Base):
    __tablename__="ranking_models"; id:Mapped[str]=mapped_column(String,primary_key=True); version:Mapped[str]=mapped_column(String,unique=True,index=True); model_type:Mapped[str]=mapped_column(String); feature_schema_version:Mapped[str]=mapped_column(String); parameters:Mapped[dict]=mapped_column(JSON); calibration:Mapped[dict]=mapped_column(JSON,default=dict); metrics:Mapped[dict]=mapped_column(JSON,default=dict); training_window:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[str]=mapped_column(String,default="candidate",index=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class BanditState(Base):
    __tablename__="bandit_states"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); context_key:Mapped[str]=mapped_column(String,index=True); policy_version:Mapped[str]=mapped_column(String); parameters:Mapped[dict]=mapped_column(JSON); sample_count:Mapped[int]=mapped_column(Integer,default=0); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PreferenceDriftEvent(Base):
    __tablename__="preference_drift_events"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); context_key:Mapped[str]=mapped_column(String,index=True); feature_key:Mapped[str]=mapped_column(String); long_term_value:Mapped[float]=mapped_column(Float); recent_value:Mapped[float]=mapped_column(Float); magnitude:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String,default="detected"); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,index=True)
class EvaluationRun(Base):
    __tablename__="evaluation_runs"; id:Mapped[str]=mapped_column(String,primary_key=True); model_version:Mapped[str]=mapped_column(String,index=True); split_strategy:Mapped[str]=mapped_column(String); metrics:Mapped[dict]=mapped_column(JSON); ablations:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class PolicyAssignment(Base):
    __tablename__="policy_assignments"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id"),index=True); experiment_key:Mapped[str]=mapped_column(String,index=True); variant:Mapped[str]=mapped_column(String,index=True); assigned_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class AccessLog(Base):
    __tablename__="access_logs"; id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); actor:Mapped[str]=mapped_column(String); action:Mapped[str]=mapped_column(String,index=True); resource_type:Mapped[str]=mapped_column(String); resource_id:Mapped[str|None]=mapped_column(String); purpose:Mapped[str]=mapped_column(String); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class StylingSession(Base):
    __tablename__="styling_sessions"; session_id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(String,index=True); turns:Mapped[list]=mapped_column(JSON,default=list); last_handoff:Mapped[dict]=mapped_column(JSON,default=dict); last_outfits:Mapped[list]=mapped_column(JSON,default=list); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
