"""V2 personalization and V3 proactive agent
Revision ID: 0002_personal_agent
"""
from alembic import op
import sqlalchemy as sa
revision="0002_personal_agent";down_revision="0001_core";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("context_profiles",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("context_key",sa.String(),index=True),sa.Column("weights",sa.JSON()),sa.Column("preferences",sa.JSON()),sa.Column("sample_count",sa.Integer()),sa.Column("updated_at",sa.DateTime()))
    op.create_table("behavior_features",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("context_key",sa.String(),index=True),sa.Column("feature_key",sa.String(),index=True),sa.Column("value",sa.Float()),sa.Column("evidence_count",sa.Integer()),sa.Column("source",sa.String()),sa.Column("updated_at",sa.DateTime()))
    op.create_table("wardrobe_item_relations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("source_item_id",sa.String(),index=True),sa.Column("target_item_id",sa.String(),index=True),sa.Column("relation_type",sa.String()),sa.Column("score",sa.Float()),sa.Column("evidence",sa.JSON()),sa.Column("updated_at",sa.DateTime()))
    op.create_table("weekly_plans",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("start_date",sa.String(),index=True),sa.Column("status",sa.String()),sa.Column("version",sa.Integer()),sa.Column("summary",sa.JSON()),sa.Column("created_at",sa.DateTime()))
    op.create_table("plan_days",sa.Column("id",sa.String(),primary_key=True),sa.Column("plan_id",sa.String(),sa.ForeignKey("weekly_plans.id"),index=True),sa.Column("date",sa.String(),index=True),sa.Column("occasion",sa.String()),sa.Column("weather",sa.JSON()),sa.Column("item_ids",sa.JSON()),sa.Column("status",sa.String()),sa.Column("explanation",sa.JSON()),sa.Column("affected_by",sa.JSON()))
    op.create_table("travel_plans",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("destination",sa.String()),sa.Column("start_date",sa.String()),sa.Column("end_date",sa.String()),sa.Column("constraints",sa.JSON()),sa.Column("result",sa.JSON()),sa.Column("created_at",sa.DateTime()))
    op.create_table("style_identities",sa.Column("user_id",sa.String(),primary_key=True),sa.Column("signature_colors",sa.JSON()),sa.Column("silhouettes",sa.JSON()),sa.Column("core_item_ids",sa.JSON()),sa.Column("preferred_formality",sa.Float()),sa.Column("exploration_range",sa.JSON()),sa.Column("context_expressions",sa.JSON()),sa.Column("evolution",sa.JSON()),sa.Column("confidence",sa.Float()),sa.Column("updated_at",sa.DateTime()))
    op.create_table("authorized_integrations",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("provider",sa.String()),sa.Column("scopes",sa.JSON()),sa.Column("status",sa.String()),sa.Column("encrypted_credential_ref",sa.String()),sa.Column("last_synced_at",sa.DateTime()),sa.Column("created_at",sa.DateTime()))
    op.create_table("proactive_events",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("event_type",sa.String(),index=True),sa.Column("importance",sa.Float()),sa.Column("scheduled_for",sa.DateTime(),index=True),sa.Column("payload",sa.JSON()),sa.Column("status",sa.String()),sa.Column("dedupe_key",sa.String(),index=True),sa.Column("created_at",sa.DateTime()))
    op.create_table("notification_preferences",sa.Column("user_id",sa.String(),primary_key=True),sa.Column("enabled",sa.Boolean()),sa.Column("important_events_only",sa.Boolean()),sa.Column("weather_change_threshold",sa.Float()),sa.Column("reminder_time",sa.String()),sa.Column("quiet_hours",sa.String()),sa.Column("channels",sa.JSON()))
    op.create_table("multi_scene_plans",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("date",sa.String()),sa.Column("scenes",sa.JSON()),sa.Column("base_item_ids",sa.JSON()),sa.Column("transitions",sa.JSON()),sa.Column("carry_item_ids",sa.JSON()),sa.Column("created_at",sa.DateTime()))
    op.create_table("purchase_analyses",sa.Column("id",sa.String(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("candidate",sa.JSON()),sa.Column("result",sa.JSON()),sa.Column("decision",sa.String()),sa.Column("created_at",sa.DateTime()))
    op.create_table("recommendation_evidence",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("outfit_id",sa.String(),index=True),sa.Column("dimension",sa.String()),sa.Column("score",sa.Float()),sa.Column("reasons",sa.JSON()),sa.Column("source_refs",sa.JSON()))
    op.create_table("access_logs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.String(),index=True),sa.Column("actor",sa.String()),sa.Column("action",sa.String(),index=True),sa.Column("resource_type",sa.String()),sa.Column("resource_id",sa.String()),sa.Column("purpose",sa.String()),sa.Column("metadata_json",sa.JSON()),sa.Column("created_at",sa.DateTime()))

def downgrade():
    for name in ["access_logs","recommendation_evidence","purchase_analyses","multi_scene_plans","notification_preferences","proactive_events","authorized_integrations","style_identities","travel_plans","plan_days","weekly_plans","wardrobe_item_relations","behavior_features","context_profiles"]:op.drop_table(name)
