"""Add reproducible ranking decisions, outcomes, models and bandit state."""
from alembic import op
import sqlalchemy as sa

revision="0007_learning_decisions";down_revision="0006_image_assets";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("recommendation_decisions",sa.Column("id",sa.String(255),primary_key=True),sa.Column("user_id",sa.String(255),sa.ForeignKey("users.id"),nullable=False,index=True),sa.Column("context_key",sa.String(255),nullable=False,index=True),sa.Column("request_snapshot",sa.JSON(),nullable=False),sa.Column("candidate_generator_version",sa.String(255),nullable=False),sa.Column("feature_schema_version",sa.String(255),nullable=False),sa.Column("ranking_model_version",sa.String(255),nullable=False),sa.Column("policy_version",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,index=True))
    op.create_table("candidate_impressions",sa.Column("id",sa.String(255),primary_key=True),sa.Column("decision_id",sa.String(255),sa.ForeignKey("recommendation_decisions.id"),nullable=False,index=True),sa.Column("user_id",sa.String(255),sa.ForeignKey("users.id"),nullable=False,index=True),sa.Column("item_ids",sa.JSON(),nullable=False),sa.Column("feature_snapshot",sa.JSON(),nullable=False),sa.Column("base_score",sa.Float(),nullable=False),sa.Column("predicted_probability",sa.Float(),nullable=False),sa.Column("uncertainty",sa.Float(),nullable=False),sa.Column("final_score",sa.Float(),nullable=False),sa.Column("position",sa.Integer()),sa.Column("displayed",sa.Boolean(),nullable=False,index=True),sa.Column("selection_probability",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,index=True))
    op.create_table("decision_outcomes",sa.Column("id",sa.Integer(),primary_key=True,autoincrement=True),sa.Column("decision_id",sa.String(255),sa.ForeignKey("recommendation_decisions.id"),nullable=False,index=True),sa.Column("impression_id",sa.String(255),sa.ForeignKey("candidate_impressions.id"),nullable=False,index=True),sa.Column("outfit_id",sa.String(255),sa.ForeignKey("outfits.id"),nullable=False,index=True),sa.Column("reward",sa.Float(),nullable=False),sa.Column("adopted",sa.Boolean(),nullable=False),sa.Column("replaced_item_ids",sa.JSON(),nullable=False),sa.Column("feedback_delay_seconds",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,index=True))
    op.create_table("ranking_models",sa.Column("id",sa.String(255),primary_key=True),sa.Column("version",sa.String(255),nullable=False,unique=True,index=True),sa.Column("model_type",sa.String(255),nullable=False),sa.Column("feature_schema_version",sa.String(255),nullable=False),sa.Column("parameters",sa.JSON(),nullable=False),sa.Column("calibration",sa.JSON(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("training_window",sa.JSON(),nullable=False),sa.Column("status",sa.String(255),nullable=False,index=True),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("bandit_states",sa.Column("id",sa.String(255),primary_key=True),sa.Column("user_id",sa.String(255),sa.ForeignKey("users.id"),nullable=False,index=True),sa.Column("context_key",sa.String(255),nullable=False,index=True),sa.Column("policy_version",sa.String(255),nullable=False),sa.Column("parameters",sa.JSON(),nullable=False),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False))
    op.create_table("preference_drift_events",sa.Column("id",sa.String(255),primary_key=True),sa.Column("user_id",sa.String(255),sa.ForeignKey("users.id"),nullable=False,index=True),sa.Column("context_key",sa.String(255),nullable=False,index=True),sa.Column("feature_key",sa.String(255),nullable=False),sa.Column("long_term_value",sa.Float(),nullable=False),sa.Column("recent_value",sa.Float(),nullable=False),sa.Column("magnitude",sa.Float(),nullable=False),sa.Column("status",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,index=True))
    op.create_table("evaluation_runs",sa.Column("id",sa.String(255),primary_key=True),sa.Column("model_version",sa.String(255),nullable=False,index=True),sa.Column("split_strategy",sa.String(255),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("ablations",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("policy_assignments",sa.Column("id",sa.String(255),primary_key=True),sa.Column("user_id",sa.String(255),sa.ForeignKey("users.id"),nullable=False,index=True),sa.Column("experiment_key",sa.String(255),nullable=False,index=True),sa.Column("variant",sa.String(255),nullable=False,index=True),sa.Column("assigned_at",sa.DateTime(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False))

def downgrade():
    for table in ("policy_assignments","evaluation_runs","preference_drift_events","bandit_states","decision_outcomes","candidate_impressions","ranking_models","recommendation_decisions"):op.drop_table(table)
