"use client";

import { ChangeEvent, ClipboardEvent as ReactClipboardEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AppImage } from "../../components/AppImage";
import { AppShell } from "../../components/AppShell";
import { API_URL, analyzeOutfitForWardrobe, fetchWardrobe, importWardrobeLink, renderCleanWardrobeImage, uploadWardrobeItem, WardrobeItem, WardrobeSuggestion } from "../../lib/wardrobeApi";

type Draft = { id:string;file:File;preview:string;source:string;category:string;subcategory:string;color:string;materials:string;materialConfidence:number;pattern:string;length:string;weatherConstraints:string;fit:string;wearingLayer:string;warmth:number;formality:number;seasons:string;styles:string;renderState:"reference"|"generating"|"ready"|"error" };
type SourcePreview={id:string;url:string;name:string};
function makeDraft(file:File,item:WardrobeSuggestion,source:string,renderState:Draft["renderState"]="ready"):Draft{return{id:crypto.randomUUID(),file,preview:URL.createObjectURL(file),source,category:item.category,subcategory:item.subcategory,color:item.color,materials:(item.material_guess||[]).join(","),materialConfidence:item.material_confidence??0,pattern:item.pattern||"待确认",length:item.length||"待确认",weatherConstraints:(item.weather_constraints||[]).join(","),fit:item.fit||"常规",wearingLayer:item.wearing_layer||"主上装",warmth:item.warmth_level??2,formality:item.formality_level??3,seasons:(item.seasons||["四季"]).join(","),styles:(item.styles||[]).join(","),renderState}}
function itemFile(source:File,item:WardrobeSuggestion){if(!item.crop_image_data)return source;const bytes=Uint8Array.from(atob(item.crop_image_data),c=>c.charCodeAt(0));return new File([bytes],`${item.subcategory||"单品"}.jpg`,{type:item.crop_mime_type||"image/jpeg"})}

export default function Upload(){
  const router=useRouter();const[drafts,setDrafts]=useState<Draft[]>([]),[sources,setSources]=useState<SourcePreview[]>([]),[wardrobe,setWardrobe]=useState<WardrobeItem[]>([]),[productUrl,setProductUrl]=useState(""),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetchWardrobe().then(setWardrobe).catch(()=>undefined)},[]);
  const duplicates=useMemo(()=>new Set(drafts.filter((d,i)=>{const name=d.subcategory.trim().toLocaleLowerCase("zh-CN");return wardrobe.some(x=>x.subcategory.trim().toLocaleLowerCase("zh-CN")===name)||drafts.slice(0,i).some(x=>x.subcategory.trim().toLocaleLowerCase("zh-CN")===name)}).map(x=>x.id)),[drafts,wardrobe]);
  const update=(id:string,patch:Partial<Draft>)=>setDrafts(xs=>xs.map(x=>x.id===id?{...x,...patch}:x));
  const remove=(id:string)=>setDrafts(xs=>{const target=xs.find(x=>x.id===id);if(target)URL.revokeObjectURL(target.preview);return xs.filter(x=>x.id!==id)});
  async function renderCandidates(additions:Draft[]){for(let i=0;i<additions.length;i++){const draft=additions[i];update(draft.id,{renderState:"generating",source:"AI 正在生成无人单品图"});setMessage(`正在生成无人单品图 ${i+1} / ${additions.length}：${draft.subcategory}`);try{const result=await renderCleanWardrobeImage(draft.file,draft);const response=await fetch(`${API_URL}${result.result_url}`);if(!response.ok)throw new Error("单品图下载失败");const blob=await response.blob(),file=new File([blob],`${draft.subcategory}.png`,{type:blob.type||"image/png"});setDrafts(xs=>xs.map(x=>{if(x.id!==draft.id)return x;URL.revokeObjectURL(x.preview);return{...x,file,preview:URL.createObjectURL(file),source:"AI 无人单品图",renderState:"ready"}}))}catch{update(draft.id,{renderState:"error",source:"单品图生成失败"})}}}
  const showSources=(files:File[])=>setSources(xs=>[...xs,...files.map(file=>({id:crypto.randomUUID(),url:URL.createObjectURL(file),name:file.name||"粘贴的图片"}))]);
  async function discover(files:File[]){if(!files.length)return;showSources(files);setBusy(true);setMessage(`正在理解 ${files.length} 张图片并发现衣服…`);try{const groups=await Promise.all(files.map(async file=>({file,result:await analyzeOutfitForWardrobe(file)})));const additions=groups.flatMap(({file,result},i)=>result.items.map(item=>makeDraft(itemFile(file,item),item,`上传图片${files.length>1?` · 第 ${i+1} 张`:""}`,"reference")));setDrafts(xs=>[...xs,...additions]);await renderCandidates(additions);setMessage(`已从上传图片中识别 ${additions.length} 件单品。请确认名称与无人单品图后保存。`)}catch(e){setMessage(e instanceof Error?e.message:"图片识别失败")}finally{setBusy(false)}}
  const choose=async(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files||[]).filter(x=>x.type.startsWith("image/"));event.target.value="";await discover(files)};
  async function importLinkValue(value:string){const url=value.trim();if(!url){setMessage("请先粘贴商品链接");return}setBusy(true);setMessage("正在读取商品主图…");try{const result=await importWardrobeLink(url);const bytes=Uint8Array.from(atob(result.image_data),c=>c.charCodeAt(0));const file=new File([bytes],result.filename,{type:result.mime_type});showSources([file]);setDrafts(xs=>[...xs,makeDraft(file,result.suggestion,"商品链接")]);setProductUrl("");setMessage("商品主图已导入，请确认后保存。")}catch(e){setMessage(e instanceof Error?e.message:"商品链接导入失败，请改用截图")}finally{setBusy(false)}}
  const importLink=()=>importLinkValue(productUrl);
  async function acceptPastedImages(files:File[]){await discover(files)}
  async function readClipboard(){
    if(!navigator.clipboard?.read){setMessage("当前浏览器不能主动读取剪贴板，请复制图片后按 Ctrl+V");return}
    try{const entries=await navigator.clipboard.read(),files:File[]=[];for(const entry of entries){const type=entry.types.find(x=>x.startsWith("image/"));if(type){const blob=await entry.getType(type);files.push(new File([blob],`剪贴板图片-${Date.now()}.${type.split("/")[1]||"png"}`,{type}))}}
      if(files.length){await acceptPastedImages(files);return}
      if(navigator.clipboard.readText){const text=(await navigator.clipboard.readText()).trim();if(/^https?:\/\//i.test(text)){setProductUrl(text);await importLinkValue(text);return}}
      setMessage("剪贴板里没有图片或商品链接");
    }catch{setMessage("没有获得剪贴板读取权限，请直接按 Ctrl+V 粘贴")}
  }
  async function handlePaste(event:ReactClipboardEvent<HTMLElement>){const files=Array.from(event.clipboardData.items).filter(x=>x.kind==="file"&&x.type.startsWith("image/")).map(x=>x.getAsFile()).filter((x):x is File=>Boolean(x));if(files.length){event.preventDefault();await acceptPastedImages(files);return}const target=event.target as HTMLElement;if(target.tagName==="INPUT"||target.tagName==="TEXTAREA")return;const text=event.clipboardData.getData("text").trim();if(/^https?:\/\//i.test(text)){event.preventDefault();setProductUrl(text);await importLinkValue(text)}}
  async function retryRender(d:Draft){setBusy(true);await renderCandidates([d]);setBusy(false)}
  function useOwnImage(id:string,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setDrafts(xs=>xs.map(draft=>{if(draft.id!==id)return draft;URL.revokeObjectURL(draft.preview);return{...draft,file,preview:URL.createObjectURL(file),source:"自己的单品图",renderState:"ready"}}));setMessage("已使用你选择的单品图，保存时不会再等待 AI 生成")}
  async function submit(){const missing=drafts.filter(x=>!duplicates.has(x.id)&&x.renderState!=="ready");if(missing.length){setMessage(`还有 ${missing.length} 件无人单品图未生成成功，请重试、自己上传或移除后再保存。`);return}const ready=drafts.filter(x=>!duplicates.has(x.id)&&x.renderState==="ready");if(!ready.length){setMessage("没有可保存的新衣物，重复项不会再次录入");return}setSaving(true);try{for(let i=0;i<ready.length;i++){const d=ready[i],form=new FormData();form.set("file",d.file);form.set("category",d.category);form.set("subcategory",d.subcategory);form.set("color",d.color==="待确认"?"未标注":d.color);form.set("material_guess",d.materials);form.set("material_confidence",String(d.materialConfidence));form.set("pattern",d.pattern);form.set("length",d.length);form.set("weather_constraints",d.weatherConstraints);form.set("fit",d.fit);form.set("wearing_layer",d.wearingLayer);form.set("warmth_level",String(d.warmth));form.set("formality_level",String(d.formality));form.set("seasons",d.seasons);form.set("styles",d.styles);await uploadWardrobeItem(form);setMessage(`正在保存 ${i+1} / ${ready.length} 件…`)}const firstRun=window.location.search.includes("from=onboarding");setMessage(firstRun?`已保存 ${ready.length} 件衣物，正在生成你的第一套推荐…`:`已保存 ${ready.length} 件衣物${duplicates.size?`，跳过 ${duplicates.size} 件重复项`:""}`);setTimeout(()=>router.push(firstRun?"/today":"/wardrobe"),600)}catch(e){setMessage(e instanceof Error?e.message:"批量保存失败")}finally{setSaving(false)}}
  return <AppShell title="让衣橱自己长出来"><main onPaste={handlePaste}>
    <div className="wardrobe-import-hero"><span className="pill green">轻量建档</span><h1 className="title">把图片交给系统，衣橱自己长出来。</h1><p className="subtle">整身照、历史照片、商品截图都可以一起上传，系统会自动判断并提取衣服。</p></div>
    <section className="card wardrobe-import-panel"><div><span className="pill">统一上传</span><h2>拍照、选图或直接粘贴</h2><p className="subtle">不用先选择图片类型；支持单张、多选、剪贴板图片和商品链接。</p></div>
      <div className="product-link-row"><input className="input" value={productUrl} onChange={e=>setProductUrl(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void importLink()}} placeholder="也可以粘贴商品页或商品图片链接"/><button className="button button-primary" disabled={busy} onClick={importLink}>从链接导入</button></div>
      <div className="upload-actions"><label className={`button button-primary ${busy?"disabled":""}`}>＋ 拍照 / 选择图片<input hidden multiple disabled={busy} type="file" accept="image/*" onChange={choose}/></label><button type="button" className="button button-ghost" disabled={busy} onClick={readClipboard}>从剪贴板粘贴</button><span className="subtle">支持多选，也可以复制图片或商品链接后直接按 Ctrl+V</span></div>
    </section>
    {sources.length>0&&<section className="uploaded-source-section"><div className="candidate-head"><div><h2>已上传的图片</h2><p className="subtle">这些原图只用于识别和生成单品图，不会作为衣橱封面保存。</p></div><span>{sources.length} 张</span></div><div className="uploaded-source-grid">{sources.map(source=><figure key={source.id}><AppImage src={source.url} alt={source.name}/><figcaption>{source.name}</figcaption></figure>)}</div></section>}
    {message&&<div className="try-on-message">{busy?"⌛ ":""}{message}</div>}
    {drafts.length>0&&<><div className="candidate-head"><div><h2>确认候选衣物</h2><p className="subtle">名称、品类或颜色不准可以直接修改；疑似重复项默认跳过。</p></div><span>{drafts.length} 件候选</span></div>
      {/* useOwnImage is an input handler, not a React Hook. */}
      {/* eslint-disable-next-line react-hooks/rules-of-hooks */}
      <div className="grid grid-2">{drafts.map(d=><article className="card wardrobe-candidate" key={d.id} style={{borderColor:duplicates.has(d.id)?"#c66":d.renderState==="error"?"#c66":d.renderState!=="ready"?"#cf9a59":undefined}}><div><div className="candidate-image"><AppImage src={d.preview} alt="衣物来源预览"/><span>{d.source}</span></div><label className="candidate-own-image">上传自己的单品图（可选）<input hidden type="file" accept="image/*" onChange={e=>useOwnImage(d.id,e)}/></label></div><div className="form-grid"><div className="field"><label>名称</label><input className="input" value={d.subcategory} onChange={e=>update(d.id,{subcategory:e.target.value})}/></div><div className="field"><label>品类</label><select className="input" value={d.category} onChange={e=>update(d.id,{category:e.target.value})}>{["上装","下装","连衣裙","外套","鞋履","配饰","包袋"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>颜色</label><input className="input" value={d.color} onChange={e=>update(d.id,{color:e.target.value})}/></div><div className="field"><label>穿着层级</label><select className="input" value={d.wearingLayer} onChange={e=>update(d.id,{wearingLayer:e.target.value})}>{["内搭","主上装","外搭","不可叠穿"].map(x=><option key={x}>{x}</option>)}</select></div><details className="candidate-more"><summary>更多属性（系统已识别，可修改）</summary><div className="form-grid"><div className="field"><label>材质推测</label><input className="input" value={d.materials} onChange={e=>update(d.id,{materials:e.target.value})} placeholder="看不清则留空"/></div><div className="field"><label>图案</label><input className="input" value={d.pattern} onChange={e=>update(d.id,{pattern:e.target.value})}/></div><div className="field"><label>长度</label><input className="input" value={d.length} onChange={e=>update(d.id,{length:e.target.value})}/></div><div className="field"><label>版型</label><input className="input" value={d.fit} onChange={e=>update(d.id,{fit:e.target.value})}/></div><div className="field"><label>季节</label><input className="input" value={d.seasons} onChange={e=>update(d.id,{seasons:e.target.value})}/></div><div className="field"><label>风格</label><input className="input" value={d.styles} onChange={e=>update(d.id,{styles:e.target.value})}/></div><div className="field"><label>天气限制</label><input className="input" value={d.weatherConstraints} onChange={e=>update(d.id,{weatherConstraints:e.target.value})}/></div></div></details>{d.renderState==="generating"&&<div className="clean-photo-required"><b>正在生成无人单品图…</b><span>人物与背景不会保存进衣橱</span></div>}{d.renderState==="error"&&<button className="button button-ghost" onClick={()=>retryRender(d)}>重新生成无人单品图</button>}<div className="toolbar">{duplicates.has(d.id)&&<span className="pill orange">名称重复，不会加入衣橱</span>}<button className="text-action" onClick={()=>remove(d.id)}>移除</button></div></div></article>)}</div>
      <div className="wardrobe-save-bar"><div><b>{drafts.filter(x=>!duplicates.has(x.id)&&x.renderState==="ready").length} 件可以加入</b><span> · {drafts.filter(x=>!duplicates.has(x.id)&&x.renderState!=="ready").length} 件生成中或失败 · {duplicates.size} 件疑似重复</span></div><button className="button button-primary" disabled={saving||busy} onClick={submit}>{saving?"保存中…":"确认加入衣橱"}</button></div></>}
  </main></AppShell>
}
